name: Building Page

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7 
      - name: Restore Previous Cache
        id: cache-build-restore
        uses: actions/cache/restore@main
        with:
          path: |
            .haxelib/
          key: cache-haxelib
      - name: Installing Libraries
        run:
          haxelib setup ~/haxelib
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib install dox
          haxelib install format
          haxelib list
      - name: Build Page
        run:
          chmod +x docs/docs.sh
          docs/docs.sh
      - name: github-actions deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: pages
          token: ${{ secrets.GH_PAT }}
      - name: Clear Previous Cache
        uses: actions/github-script@main
        with:
          script: await require('./actions/cache/clear-cache.js')({github, context}, 'cache-haxelib');      
      - name: Save Current Cache
        uses: actions/cache@main
        with:
          key: cache-haxelib
          path: |
            .haxelib/
          restore-keys: |
            cache-haxelib
